USB_VID = 0x239A
USB_PID = 0x8114
USB_PRODUCT = "LilyGO T-Dongle S3"
USB_MANUFACTURER = "LilyGO"

IDF_TARGET = esp32s3

CIRCUITPY_ESP_FLASH_MODE = qio
CIRCUITPY_ESP_FLASH_FREQ = 80m
CIRCUITPY_ESP_FLASH_SIZE = 16MB

CIRCUITPY_BITBANG_APA102 = 1